import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '@/components/Hero'
import Technology from '@/components/Technology'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Portfolio | Trung Ung</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Hero />
				<Technology />
			</main>
		</>
	)
}

export default Home
