import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '@/components/Hero'
import Technology from '@/components/Technology'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'

const Home: NextPage = () => {
	return (
		<div className="scroll-smooth">
			<Head>
				<title>Portfolio | Trung Ung</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Hero />
				<Technology />
				<Projects />
				<Contact />
				<Footer />
			</main>
		</div>
	)
}

export default Home
