import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '@/components/Hero'
import Technology from '@/components/Technology'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Script from 'next/script'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Portfolio | Trung Ung</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{process.env.NODE_ENV === 'production' && (
				<>
					<Script
						src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_ANALYTICS_ID}`}
						strategy="afterInteractive"
					/>
					<Script id="google-analytics" strategy="afterInteractive">
						{`
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){window.dataLayer.push(arguments);}
	  gtag('js', new Date());
	  gtag('config', '${process.env.NEXT_PUBLIC_ANALYTICS_ID}');
	`}
					</Script>
				</>
			)}

			<main>
				<Header />
				<Hero />
				<Technology />
				<Projects />
				<Contact />
				<Footer />
			</main>
		</div>
	)
}

export default Home
